Add practice for trunk based development
Minimum-CD/cd-manifesto pull request #234
Opened 2022-08-30 11:49 UTC by bdfinst

Add practice for trunk based development

2022-08-30 22:58 UTC, tracybannon requested changes
Why did you remove https://trunkbaseddevelopment.com/  in the minimum activities for CI section

2022-08-31 03:47 UTC, Jerreck commented
> Why did you remove https://trunkbaseddevelopment.com/ in the minimum activities for CI section

It looks like the link is there in the new section he's added that expands more on TBD.  The Minimums link links to that new section.

2022-08-31 11:17 UTC, tracybannon approved these changes

2022-08-31 11:17 UTC, tracybannon commented
Thanks for the grammar and tweaks and moving the TBD inside to expand!

2022-08-31 11:17 UTC, closed without merging